# .github/workflows/security-audit.yml
#
# Security audit workflow for GitHub Actions.
# Copy this file to .github/workflows/ in your repository.
#
# Results appear in the Security tab (only visible to repo writers).
# The workflow itself just passes/fails — no vulnerability details in logs.

name: Security Audit

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      profile:
        description: 'Scan profile'
        required: false
        default: 'standard'
        type: choice
        options:
          - quick
          - standard
          - deep

permissions:
  contents: read
  security-events: write  # Required for SARIF upload to Security tab

jobs:
  security-audit:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for gitleaks

      # --- Tool Installation ---

      - name: Install gitleaks
        run: |
          GITLEAKS_VERSION=$(curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest | jq -r .tag_name)
          curl -sSfL "https://github.com/gitleaks/gitleaks/releases/download/${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION#v}_linux_x64.tar.gz" | tar xz -C /usr/local/bin gitleaks

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python tools
        run: pip install bandit

      - name: Install semgrep
        run: pip install semgrep

      - name: Set up Node (if needed)
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Cache trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}-${{ github.run_id }}
          restore-keys: trivy-db-${{ runner.os }}-

      - name: Install trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      # --- Run Scan ---
      # The security-audit CLI is NOT installed globally. Copy bin/security-audit
      # from the skill into your repo (e.g. .github/scripts/security-audit) and
      # reference it by path here.

      - name: Security audit
        run: |
          PROFILE="${{ inputs.profile || 'quick' }}"
          .github/scripts/security-audit -p "$PROFILE" -q --sarif > results.sarif
        continue-on-error: true

      # --- Upload to Security Tab (private to repo writers) ---

      - name: Upload SARIF
        if: always() && hashFiles('results.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: security-audit
